name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        - docker build . --file Dockerfile --tag graalvm-ce:21-latest
        - docker tag graalvm-ce:21-latest ghcr.io/Reizor-Hosting/yolks/graalvm-ce:21-latest
        - docker push ghcr.io/Reizor-Hosting/yolks/graalvm-ce:21-latest
